package com.astordev.ugc.adapter.inspectedpost

import com.astordev.ugc.post.model.Post
import java.time.LocalDateTime

data class InspectedPostMessagePayload(
    val post: Post,
    val categoryName: String,
    val autoGeneratedTags: List<String>,
    val inspectedAt: LocalDateTime
)
