package com.astordev.ugc.adapter.inspectedpost

import com.astordev.ugc.inspectedpost.model.InspectedPost

fun InspectedPostMessagePayload.toModel() : InspectedPost {
    return InspectedPost(
        post,
        categoryName,
        autoGeneratedTags,
        inspectedAt
    )
}