package com.astordev.ugc.adapter.inspectedpost

import com.astordev.ugc.inspectedpost.model.InspectedPost

fun InspectedPostMessage.toModel() : InspectedPost {
    return InspectedPost(
        payload.post,
        payload.categoryName,
        payload.autoGeneratedTags,
        payload.inspectedAt
    )
}