package com.astordev.ugc.adapter.inspectedpost

import com.astordev.ugc.adapter.common.CdcMessage
import com.astordev.ugc.adapter.common.OperationType
import com.astordev.ugc.adapter.common.Topic
import com.astordev.ugc.inspectedpost.model.InspectedPost
import com.astordev.ugc.port.InspectedPostMessageProducePort
import com.astordev.ugc.post.model.PostId
import com.fasterxml.jackson.databind.ObjectMapper
import org.springframework.kafka.core.KafkaTemplate
import org.springframework.stereotype.Component

@Component
class InspectedPostMessageProduceAdapter(
    private val kafkaTemplate: KafkaTemplate<String, String>,
    private val objectMapper: ObjectMapper
): InspectedPostMessageProducePort {
    override fun sendCreateMessage(inspectedPost: InspectedPost) {
        val message = CdcMessage.of(inspectedPost.post.id.long, OperationType.CREATE, convertToPayload(inspectedPost))
        this.sendMessage(message)
    }

    override fun sendUpdateMessage(inspectedPost: InspectedPost) {
        val message = CdcMessage.of(inspectedPost.post.id.long, OperationType.UPDATE, convertToPayload(inspectedPost))
        this.sendMessage(message)
    }

    override fun sendDeleteMessage(postId: PostId) {
        val message = CdcMessage.of<InspectedPostMessagePayload>(postId.long, OperationType.DELETE)
        this.sendMessage(message)
    }

    private fun convertToPayload(inspectedPost: InspectedPost): InspectedPostMessagePayload {
        return InspectedPostMessagePayload(
                inspectedPost.post,
                inspectedPost.categoryName,
                inspectedPost.autoGeneratedTags,
                inspectedPost.inspectedAt
            )
    }

    private fun sendMessage(message: CdcMessage<InspectedPostMessagePayload>) {
        kafkaTemplate.send(
            Topic.INSPECTED_POST,
            message.id.toString(),
            objectMapper.writeValueAsString(message)
        )
    }
}