package com.astordev.ugc.adapter.inspectedpost

import com.astordev.ugc.adapter.common.OperationType
import com.astordev.ugc.post.model.Post
import java.time.LocalDateTime

data class InspectedPostMessage (
    val id: Long,
    val operationType: OperationType,
    val payload: Payload
) {
    data class Payload(
        val post: Post,
        val categoryName: String,
        val autoGeneratedTags: List<String>,
        val inspectedAt: LocalDateTime
    )
}