package com.astordev.ugc.inspectedpost.model

import com.astordev.ugc.post.model.Post
import java.time.LocalDateTime

class InspectedPost(
    val post: Post,
    val categoryName: String,
    val autoGeneratedTags: List<String>,
    val inspectedAt: LocalDateTime
) {
    companion object {
        fun generate(
            post: Post,
            categoryName: String,
            autoGeneratedTags: List<String>
        ): InspectedPost {
            return InspectedPost(
                post,
                categoryName,
                autoGeneratedTags,
                LocalDateTime.now()
            )
        }
    }
}