package com.astordev.ugc.postsearch

import com.astordev.ugc.inspectedpost.model.InspectedPost
import java.time.LocalDateTime


fun InspectedPost.toDocument(): PostDocument {
    return PostDocument(
        this.post.id.long,
        this.post.title,
        this.post.content,
        this.categoryName,
        this.autoGeneratedTags,
        LocalDateTime.now()
    )
}